### ISSUE TITLE
FeatReq: basic_auth_required accepting callable

### ISSUE THREAD

**Issue by yiga2** [pgjones/quart-auth#1]
Currently `basic_auth_required` is a bit simplistic and "dangerous" as the credentials are stored in the code. I suggest replacing the args of the wrapper by a single callable function which:
1. could do the same as currently, that is, comparing user and password values
2. address other use cases like validating user/password in an external API for instance

The latter is what I am after as "our" quart API acts as a middleman to an external API. We pass (aiohttp.ClientSession) user and password to its login page and if we get a token back (sessionId), it's validated. We then use that cookie in further calls.

**Comment by pgjones** [comment]
The credentials are stored in the app's config, which can be loaded from the environment or files (no need to store credentials in the code). 

I'm not sure whether to add this functionality to Quart-Auth directly - it is quite easily to adapt and create your own basic_auth_required decorator based on the existing one e.g. for your use case (with `check_auth`):
```python
def basic_auth_required(func: Callable) -> Callable:
    @wraps(func)
    async def wrapper(*args: Any, **kwargs: Any) -> Any:
        if has_request_context():
            auth = request.authorization
        elif has_websocket_context():
            auth = websocket.authorization
        else:
            raise RuntimeError("Not used in a valid request/websocket context")

        valid = await check_auth(auth)
        if valid:
            return await current_app.ensure_async(func)(*args, **kwargs)
        else:
            raise UnauthorizedBasicAuth()

    return wrapper
```

**Comment by yiga2** [comment]
qq: do you monitor more  - and do you prefer keep logs in - gitter, gitlab or github ? There are many channels you mentioned ;-)

**Comment by pgjones** [comment]
I'm currently moving everything to github (watch this space...).

**Comment by yiga2** [comment]
Just discovered a possible bug: when executing the wrapped function (past validation), if the function/view has no argument, you get `TypeError: xxxx() takes 0 positional arguments but 2 were given`
Workaround - for now - is to add a dummy arg array in the view definition i.e. `async def xxx(*dummy_args):`

**Comment by pgjones** [comment]
Hmm, I'm not sure why it would error like that - could you share the stack trace?

**Comment by yiga2** [comment]
OMG - embarrassing:
```
    @wraps(func)
    async def wrapper(*args, **kwargs):
        print_log(f'{session=}, {vars(session)}')
        if auth := request.authorization:
            if 'iw_cookies' not in session:
                if request.method == 'POST':
                    args = (await request.get_json()).get('userDefinedContext')
```
... I am reassigning `args` later in the code. Sorry for the oversight.

**Comment by pgjones** [comment]
No worries, thanks for clarifying - a mystery closed :).
