### ISSUE TITLE
QUART_AUTH cookie missing.

### ISSUE THREAD

**Issue by skwzrd** [pgjones/quart-auth#11]
When running the following locally (on Windows 10) with quart 0.18.4, quart-wtforms 1.0.0, and quart-auth 0.9.0, a QUART_AUTH cookie appears, but when running it remotely (on CentOS), the QUART_AUTH cookie isn't populated in the browser. The form loads, successfully submits, and after the line `login_user(AuthUser(UserType.viewer.value))`, I'd expect to have the cookie. I've swapped `return redirect(url_for('home'))` for `return 123` and the same thing happens -- cookie is populated when running quart locally, but not remotely. I am not using a reverse-proxy or anything. Just hypercorn (`hypercorn main:app -b 0.0.0.0:8080 -w 2`) and the dev server (`py main.py`).

The firewall is open on port 8080, and the page loads from the remote server. I've also set this up with Docker, and the same issue occurs.

```py
@app.route("/login", methods=['GET', 'POST'])
async def login():
    form = await LoginForm.create_form()
    if await form.validate_on_submit():
        if form.username.data == UserType.viewer.value and compare_digest(form.password.data, os.getenv('PASSWORD_VIEWER')):
            login_user(AuthUser(UserType.viewer.value))
            return redirect(url_for('home'))
        else:
            form.form_errors.append('Incorrect credentials')
    return await render_template('login.html', form=form)
```

Any ideas as to why this is happening?

**Comment by skwzrd** [comment]
So, I wasn't using https. To get https working with hypercorn, I generate certs with

```
openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem
```

and ran hypercorn with

```
sudo ./virt_env/bin/hypercorn --certfile cert.pem --keyfile key.pem -b 0.0.0.0:8080 -w 1 main:app
```

**Comment by pgjones** [comment]
See also [docs on disabling secure cookies for dev](https://quart-auth.readthedocs.io/en/latest/how_to_guides/developing.html)
