### ISSUE TITLE
Nginx reverse proxy error

### ISSUE THREAD

**Issue by Sincejunly** [pgjones/quart-auth#12]
In most cases, it runs well, but when I access it using the regional network IP, it seems to be unable to log in properly
Of course, it does not include the local 127.0.01
No matter how I modify it ``` request.remote_addr```will always be 127.0.0.1
nginx:
``` 
 location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_redirect off;
    proxy_pass http://127.0.0.1:5000;

  }
```
py:
```
auth_manager = QuartAuth()
def create_app():
    app = Quart(__name__, template_folder='auth')
    auth_manager.init_app(app)
    return app
app = create_app()

@app.before_serving
async def setup():
    global app,event,domains
    event = asyncio.Event()
    app = cors(app, allow_origin=domains)
    Session(app)

    await registerUser()

@app.route('/login', methods=['GET', 'POST'])
async def login():
    print(request.remote_addr)
    userU = await request.get_json()
    login_user(AuthUser(userU['id']))

@app.route('/check', methods=['GET', 'POST'])
async def check():
    print(await current_user.is_authenticated)
```

In addition, after testing, it has been found that ```@app. websocket``` cannot support the wss protocol and can perform ws connections normally. I am now using websockets as the wss router

Hope to add traffic forwarding function in the future

**Comment by Sincejunly** [comment]
After some attempts, I directly accessed the server's 5000 port, but I still couldn't detect the login status
![image](https://github.com/pgjones/quart-auth/assets/96775034/3460bf41-f182-48d0-ae51-9c996631dd8e)

**Comment by Sincejunly** [comment]
Okay, I see it https://github.com/pgjones/quart-auth/issues/11 But I still have some unresolved issues

**Comment by pgjones** [comment]
Yep, this is likely a secure cookie issue as the connection between nginx and your app isn't secure.
