### ISSUE TITLE
QuartAuth().user_class as init argument

### ISSUE THREAD

**Issue by Henkhogan** [pgjones/quart-auth#13]
I find myself writing 

```
auth_manager = QuartAuth(salt = my_salt)
auth_manager.user_class = my_user_class
auth_manager.init_app(app)
```

where I would prefer to write 

`QuartAuth(app, salt = my_salt, user_class=my_user_class)`

If you are fine with that, I would file a PR. 
-> would you mind switching to dataclasses to get rid of the boilerplate QuartAuth.__init__() method code

**Comment by pgjones** [comment]
Seems like a good idea, 1aa96b50b09a38042c8bbdd0de0b2a606db61ab3

I'm not convinced a dataclass would help here.
