### ISSUE TITLE
0.10.0 breaks derived AuthUser classes

### ISSUE THREAD

**Issue by rthalley** [pgjones/quart-auth#17]
QuartAuth taking a user_class argument that defaults to AuthUser means that the prior way of overriding the class of setting the user_class attribute of the class doesn't work.

I had code which did:

class ApiUser(AuthUser):
    ...

class ApiAuth(QuartAuth):
   user_class = ApiUser

And this code broke in 0.10.0 because now self.user_class is always initialized to AuthUser.

I wonder if for backwards compatibility these should not default to None and then get initialized from the class's attribute.  Alternatively, I suppose you could deprecate the old way.

**Comment by pgjones** [comment]
Yep, that was a mistake, fixed in 0.10.1. Thanks.
