### ISSUE TITLE
How to create a user class with AuthUser and SQLAlchemy?

### ISSUE THREAD

**Issue by Nicolas-M15** [pgjones/quart-auth#7]
I'm using a MySQL database that increment user automatically.

Nevertheless, quart_auth requires an __init__ function and an auth_id that aren't buit to do automated incrementation with SQL Alchemy.

Here is the piece of code I have:

```
class users(AuthUser, db.Model):
    
    def __init__(self, id):
        super().__init__(id)
        self._auth_id= id
        self._resolved = False
        self.email = None
    
    async def _resolve(self):
        if not self._resolved:
            self.email = await db.fetch_email(self.id)
            self._resolved = True
            
    __tablename__ = 'users'

    async def get_id(self):
    # this matches what user_loader needs to uniquely load a user
        return self.id
    
    #id = db.Column('id', db.Integer, primary_key = True)
    id = db.Column(db.Integer, primary_key=True, unique=True , autoincrement=True)
```

Unfortunatelly, I get JSON encoding error, probably due to the AuthUser structure.

How can I have automated user_id incrementation with SQLALchemy and use it with AuthUser correctly?

Many thanks

**Comment by pgjones** [comment]
There is a possible pattern in the docs, https://quart-auth.readthedocs.io/en/latest/how_to_guides/extending.html

**Comment by pgjones** [comment]
Please reopen if it isn't clear.
