### ISSUE TITLE
Configuration does not seem to be respected

### ISSUE THREAD

**Issue by briancurtin** [pgjones/quart-auth#8]
I have the following environment variables set:

```
QUART_DEBUG=True
QUART_SECRET_KEY=<redacted>
QUART_AUTH_COOKIE_NAME=VMS
QUART_AUTH_COOKIE_SAMESITE=Lax
QUART_AUTH_COOKIE_SECURE=False
```

and the following snippet of code to initialize the app:

```python3
app = Quart(__name__)
app.config.from_prefixed_env()

auth_manager = AuthManager(app)

logger.info(event="Configuration at startup", **app.config)
```

So when the app starts out it is currently dumping out the app config, which shows the following (unrelated things removed):

`2023-02-17T22:34:55.563625Z [info     ] Configuration at startup       AUTH_COOKIE_NAME=VMS AUTH_COOKIE_SAMESITE=Lax AUTH_COOKIE_SECURE=False `

So at this point it _seems_ to me like things would work. I then go to the browser and hit my login page which `POST`s to a route that calls `login_user`. That generally seems to work ok as well, but what ends up in the response headers `set-cookie` seems like it did not pay attention to the configuration.

I end up with `QUART_AUTH=<redacted>; Secure; HttpOnly; Path=/; SameSite=Lax` which means it didn't take the name or the secure value. Because I'm currently working on this locally I need at least the `SECURE=False` part, so Chrome of course rejects this since it's coming over HTTP.

I want to believe I'm just misusing something, but it looks straightforward enough and I don't see anything else I should be doing to get the config recognized. Is something not working right or am I doing it wrong? I can't really tell.

I don't imagine this is related, but for whatever it's worth Quart is running out of http://0.0.0.0:8081 (via Hypercorn) and the frontend is http://0.0.0.0:8080, and there is an Nginx reverse proxy redirecting 8080/api (the root of all Quart stuff) to 8081/api. I don't think Quart-Auth is even looking at that, but figured I'd mention it.

**Comment by pgjones** [comment]
Your environment variables need to be prefixed, the default prefix is `QUART_` hence it should be `QUART_QUART_AUTH_COOKIE_NAME` etc... (note `QUART_DEBUG` is already prefixed). As this looks weird and could be confusing I tend to use the project name as the prefix, as shown [here](https://github.com/pgjones/tozo/blob/main/backend/development.env) and then [here](https://github.com/pgjones/tozo/blob/main/backend/src/backend/run.py#L23)

**Comment by briancurtin** [comment]
I had initially tried that with `app.config.from_prefixed_env(prefix="VMS")` and then `VMS_AUTH_COOKIE_NAME`, which of course does not work now knowing that the prefix is on the `quart` _app_ side and not within `quart-auth`. Requiring a double prefix is probably worth a callout in the documentation [here](https://quart-auth.readthedocs.io/en/latest/how_to_guides/configuration.html) that the `QUART_` there needs an additional prefix depending on how your app loading its configuration. That page appears like a verbatim configuration list, which is what got me so hung up on thinking something else had to be going on.
